### General
POST https://mycloud-emails.kooqix-dev.com/general
Content-Type: application/json
Authorization: token

{
	"subject": "This is the subject",
	"body": "HTML body of the email",
	"receivers": ["kooqix.dev@gmail.com"]
}

### Check IP
POST https://mycloud-emails.kooqix-dev.com/check-ip
Content-Type: application/json

{
	"new_ip": "192.168.1.1"
}



### Error Message
POST https://mycloud-emails.kooqix-dev.com/error
Content-Type: application/json

{
	"subject": "This is the subject",
	"error_message": "This is the error message"
}


### Saturated Storage
POST https://mycloud-emails.kooqix-dev.com/saturated-storage
Content-Type: application/json

{
	"args": [
		["disk_1", 82],
		["disk_2", 90]
	]
}